using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace PbLite.Generator
{
    internal static class SerializerEmitter
    {
        public static void Generate(SourceProductionContext ctx, TypeInfo? info)
        {
            if (info == null) return;

            var sb = new StringBuilder();
            string serializerName = info.SerializerName;

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Buffers;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using PbLite;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(info.Namespace))
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"    public sealed class {serializerName} : IProtoSerializer");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static readonly {serializerName} Instance = new();");
            sb.AppendLine($"        private {serializerName}() {{ }}");
            sb.AppendLine();
            sb.AppendLine($"        public Type Type => typeof({info.FullyQualifiedName});");
            sb.AppendLine();

            if (info.IsValueType)
            {
                // Generate typed methods (no boxing)
                WriteEmitter.Generate(sb, info, isValueType: true);
                sb.AppendLine();
                WriteEmitter.GenerateGetSize(sb, info, isValueType: true);
                sb.AppendLine();
                ReadEmitter.Generate(sb, info, isValueType: true);
                sb.AppendLine();

                // Explicit IProtoSerializer interface implementation (delegates to typed methods)
                sb.AppendLine("        void IProtoSerializer.Serialize<TWriter>(TWriter writer, object value)");
                sb.AppendLine("        {");
                sb.AppendLine($"            Serialize(writer, ({info.FullyQualifiedName})value);");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        int IProtoSerializer.GetSize(object value)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return GetSize(({info.FullyQualifiedName})value);");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        object IProtoSerializer.Deserialize(ref ProtoReader reader, object? value)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return Deserialize(ref reader, ({info.FullyQualifiedName}?)value);");
                sb.AppendLine("        }");
            }
            else
            {
                WriteEmitter.Generate(sb, info);
                sb.AppendLine();
                WriteEmitter.GenerateGetSize(sb, info);
                sb.AppendLine();
                ReadEmitter.Generate(sb, info);
            }

            sb.AppendLine("    }");

            if (!string.IsNullOrEmpty(info.Namespace))
                sb.AppendLine("}");

            ctx.AddSource($"{serializerName}.g.cs", sb.ToString());
        }

        public static void GenerateRegistry(SourceProductionContext ctx, ImmutableArray<TypeInfo?> types, Compilation compilation)
        {
            var validTypes = types.Where(t => t != null).ToList();
            if (validTypes.Count == 0) return;

            string className = "PbLiteGeneratedSerializers";
            TryFindTypeNamespace(compilation.Assembly.GlobalNamespace, className, out string? ns);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using PbLite;");
            sb.AppendLine();

            string indent = "";
            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
                indent = "    ";
            }

            sb.AppendLine($"{indent}static partial class {className}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    private static bool _initialized;");
            sb.AppendLine($"{indent}    public static void Register()");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (_initialized) return;");
            foreach (var info in validTypes)
            {
                sb.AppendLine($"{indent}        global::PbLite.SerializerRegistry.Register({info!.SerializerFullName}.Instance);");
            }
            sb.AppendLine($"{indent}        _initialized = true;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");

            if (!string.IsNullOrEmpty(ns))
                sb.AppendLine("}");

            ctx.AddSource($"{className}.g.cs", sb.ToString());
        }

        /// <summary>
        /// Recursively searches for a type by name. If found, outputs its namespace
        /// (null if in global namespace). Returns false if not found.
        /// </summary>
        private static bool TryFindTypeNamespace(INamespaceSymbol nsSymbol, string typeName, out string? ns)
        {
            foreach (var typeMember in nsSymbol.GetTypeMembers())
            {
                if (typeMember.Name == typeName)
                {
                    ns = nsSymbol.IsGlobalNamespace ? null : nsSymbol.ToDisplayString();
                    return true;
                }
            }
            foreach (var nsMember in nsSymbol.GetNamespaceMembers())
            {
                if (TryFindTypeNamespace(nsMember, typeName, out ns))
                    return true;
            }
            ns = null;
            return false;
        }
    }
}