using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace PbLite.Generator
{
    internal static class SerializerEmitter
    {
        private static readonly DiagnosticDescriptor MultipleRegistriesRule = new(
            "N3PROTO003",
            "PbGenerateRegistry 重复",
            "存在多个 [PbGenerateRegistry] 标记的类，只使用 '{0}'，其余将被忽略.",
            "PbLite",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true,
            description: "整个程序集中只能有一个 [PbGenerateRegistry] 标记的类.");

        public static void Generate(SourceProductionContext ctx, TypeInfo? info)
        {
            if (info == null) return;

            var sb = new StringBuilder();
            string serializerName = info.SerializerName;

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Buffers;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using PbLite;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(info.Namespace))
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"    public sealed class {serializerName} : IProtoSerializer");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static readonly {serializerName} Instance = new();");
            sb.AppendLine($"        private {serializerName}() {{ }}");
            sb.AppendLine();
            sb.AppendLine($"        public Type Type => typeof({info.FullyQualifiedName});");
            sb.AppendLine();

            WriteEmitter.Generate(sb, info);
            sb.AppendLine();
            WriteEmitter.GenerateGetSize(sb, info);
            sb.AppendLine();
            ReadEmitter.Generate(sb, info);

            sb.AppendLine("    }");

            if (!string.IsNullOrEmpty(info.Namespace))
                sb.AppendLine("}");

            ctx.AddSource($"{serializerName}.g.cs", sb.ToString());
        }

        public static void GenerateRegistry(SourceProductionContext ctx,
            ImmutableArray<TypeInfo?> types, ImmutableArray<RegistryInfo?> registries)
        {
            var validRegistries = registries.Where(r => r != null).ToList();
            if (validRegistries.Count == 0) return;

            // Sort for deterministic "first" selection
            var sorted = validRegistries.OrderBy(r => r!.Namespace).ThenBy(r => r!.Name).ToList();
            var registry = sorted[0]!;

            // Report diagnostics for duplicates
            for (int i = 1; i < sorted.Count; i++)
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    MultipleRegistriesRule, sorted[i]!.Location, registry.Name));
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using PbLite;");
            sb.AppendLine();

            string staticKeyword = registry.IsStatic ? "static " : "";

            if (!string.IsNullOrEmpty(registry.Namespace))
            {
                sb.AppendLine($"namespace {registry.Namespace}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"    {staticKeyword}partial class {registry.Name}");
            sb.AppendLine("    {");
            sb.AppendLine("        private static void ForEach(Action<IProtoSerializer> action)");
            sb.AppendLine("        {");

            foreach (var info in types.Where(t => t != null).OrderBy(t => t!.Namespace).ThenBy(t => t!.Name))
            {
                sb.AppendLine($"            action({info!.SerializerFullName}.Instance);");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");

            if (!string.IsNullOrEmpty(registry.Namespace))
                sb.AppendLine("}");

            ctx.AddSource($"{registry.Name}.Registry.g.cs", sb.ToString());
        }
    }
}
