using Microsoft.CodeAnalysis;
using System.Linq;
using System.Text;

namespace PbLite.Generator
{
    internal static class SerializerEmitter
    {
        public static void Generate(SourceProductionContext ctx, TypeInfo? info)
        {
            if (info == null) return;

            var sb = new StringBuilder();
            string serializerName = info.Name + "Serializer";

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Buffers;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using PbLite;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(info.Namespace))
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"    public sealed class {serializerName} : IProtoSerializer");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static readonly {serializerName} Instance = new();");
            sb.AppendLine($"        private {serializerName}() {{ }}");
            sb.AppendLine();
            sb.AppendLine($"        public Type Type => typeof({info.Name});");
            sb.AppendLine();

            WriteEmitter.Generate(sb, info);
            sb.AppendLine();
            ReadEmitter.Generate(sb, info);

            sb.AppendLine("    }");

            if (!string.IsNullOrEmpty(info.Namespace))
                sb.AppendLine("}");

            ctx.AddSource($"{serializerName}.g.cs", sb.ToString());
        }

        public static void GenerateRegistry(SourceProductionContext ctx, System.Collections.Immutable.ImmutableArray<TypeInfo?> types)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using PbLite;");
            sb.AppendLine();
            sb.AppendLine("namespace PbLite");
            sb.AppendLine("{");
            sb.AppendLine("    public static class ProtoGenerated");
            sb.AppendLine("    {");
            sb.AppendLine("        public static void ForEach(Action<IProtoSerializer> action)");
            sb.AppendLine("        {");

            foreach (var info in types.Where(t => t != null).OrderBy(t => t!.Namespace).ThenBy(t => t!.Name))
            {
                string serializerName = info!.Name + "Serializer";
                string fullRef = string.IsNullOrEmpty(info.Namespace)
                    ? serializerName
                    : $"{info.Namespace}.{serializerName}";
                sb.AppendLine($"            action({fullRef}.Instance);");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            ctx.AddSource("ProtoGenerated.g.cs", sb.ToString());
        }
    }
}
