using System.Collections.Generic;
using System.Text;

namespace PbLite.ProtoGen;

class CSharpEmitter
{
    public List<(string FileName, string Content)> Emit(
        ProtoFile file, string baseName, string? overrideNamespace, bool multipleFiles)
    {
        string ns = ResolveNamespace(file, overrideNamespace);

        var allEnums = new List<ProtoEnum>();
        var allMessages = new List<ProtoMessage>();
        foreach (var m in file.Messages)
            CollectTypes(m, allMessages, allEnums);
        allEnums.AddRange(file.Enums);

        if (!multipleFiles)
        {
            var sb = new StringBuilder();
            EmitHeader(sb);
            EmitUsings(sb);
            EmitNamespaceStart(sb, ns);
            int indent = string.IsNullOrEmpty(ns) ? 0 : 1;
            foreach (var e in allEnums)
                EmitEnum(sb, e, indent);
            foreach (var m in allMessages)
                EmitMessage(sb, m, indent);
            EmitNamespaceEnd(sb, ns);
            return [(baseName + ".cs", sb.ToString())];
        }

        var results = new List<(string, string)>();
        foreach (var e in allEnums)
        {
            var sb = new StringBuilder();
            EmitHeader(sb);
            EmitUsings(sb);
            EmitNamespaceStart(sb, ns);
            EmitEnum(sb, e, string.IsNullOrEmpty(ns) ? 0 : 1);
            EmitNamespaceEnd(sb, ns);
            results.Add(($"{e.Name}.cs", sb.ToString()));
        }
        foreach (var m in allMessages)
        {
            var sb = new StringBuilder();
            EmitHeader(sb);
            EmitUsings(sb);
            EmitNamespaceStart(sb, ns);
            EmitMessage(sb, m, string.IsNullOrEmpty(ns) ? 0 : 1);
            EmitNamespaceEnd(sb, ns);
            results.Add(($"{m.Name}.cs", sb.ToString()));
        }
        return results;
    }

    private static string ResolveNamespace(ProtoFile file, string? overrideNamespace) =>
        overrideNamespace ?? file.CSharpNamespace ?? NameConverter.PackageToNamespace(file.Package);

    private static void CollectTypes(ProtoMessage msg, List<ProtoMessage> messages, List<ProtoEnum> enums)
    {
        messages.Add(msg);
        foreach (var nested in msg.NestedMessages)
            CollectTypes(nested, messages, enums);
        enums.AddRange(msg.NestedEnums);
    }

    private static void EmitHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by PbLite.ProtoGen from proto3 definition.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    private static void EmitUsings(StringBuilder sb)
    {
        sb.AppendLine("using System;");
        sb.AppendLine("using PbLite;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
    }

    private static void EmitNamespaceStart(StringBuilder sb, string ns)
    {
        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }
    }

    private static void EmitNamespaceEnd(StringBuilder sb, string ns)
    {
        if (!string.IsNullOrEmpty(ns))
            sb.AppendLine("}");
    }

    private static void EmitEnum(StringBuilder sb, ProtoEnum e, int indent)
    {
        string pad = new string(' ', indent * 4);
        if (e.Deprecated)
            sb.AppendLine($"{pad}[Obsolete]");
        sb.AppendLine($"{pad}public enum {e.Name}");
        sb.AppendLine($"{pad}{{");
        for (int i = 0; i < e.Values.Count; i++)
        {
            var v = e.Values[i];
            string name = NameConverter.EnumValueToPascalCase(v.Name);
            sb.Append($"{pad}    {name} = {v.Number}");
            sb.AppendLine(i < e.Values.Count - 1 ? "," : "");
        }
        sb.AppendLine($"{pad}}}");
        sb.AppendLine();
    }

    private static void EmitMessage(StringBuilder sb, ProtoMessage msg, int indent)
    {
        string pad = new string(' ', indent * 4);
        if (msg.Deprecated)
            sb.AppendLine($"{pad}[Obsolete]");
        sb.AppendLine($"{pad}[PbContract]");
        sb.AppendLine($"{pad}public partial class {msg.Name}");
        sb.AppendLine($"{pad}{{");
        for (int i = 0; i < msg.Fields.Count; i++)
        {
            EmitField(sb, msg.Fields[i], indent + 1);
            if (i < msg.Fields.Count - 1)
                sb.AppendLine();
        }
        sb.AppendLine($"{pad}}}");
        sb.AppendLine();
    }

    private static void EmitField(StringBuilder sb, ProtoField field, int indent)
    {
        string pad = new string(' ', indent * 4);
        string csharpName = NameConverter.ToPascalCase(field.Name);
        string csharpType = ResolveCSharpType(field);
        string? initializer = GetInitializer(field, csharpType);

        if (field.Deprecated)
            sb.AppendLine($"{pad}[Obsolete]");

        // Build attribute
        string wireAttr = "";
        if (!field.IsMap && field.Label != FieldLabel.Repeated)
        {
            if (TypeMapper.NeedsWireAttribute(field.ProtoType))
                wireAttr = $", Wire = {TypeMapper.GetWire(field.ProtoType)}";
        }
        else if (field.Label == FieldLabel.Repeated)
        {
            // For repeated scalar fields, emit wire on the element type
            if (TypeMapper.NeedsWireAttribute(field.ProtoType))
                wireAttr = $", Wire = {TypeMapper.GetWire(field.ProtoType)}";
        }

        sb.AppendLine($"{pad}[PbMember({field.Number}{wireAttr})]");
        if (initializer != null)
            sb.AppendLine($"{pad}public {csharpType} {csharpName} = {initializer};");
        else
            sb.AppendLine($"{pad}public {csharpType} {csharpName};");
    }

    private static string ResolveCSharpType(ProtoField field)
    {
        if (field.IsMap)
        {
            string keyType = ResolveTypeRef(field.MapKeyType!);
            string valType = ResolveTypeRef(field.MapValueType!);
            return $"Dictionary<{keyType}, {valType}>";
        }

        string baseType = ResolveTypeRef(field.ProtoType);

        if (field.Label == FieldLabel.Repeated)
            return $"List<{baseType}>";

        if (field.Label == FieldLabel.Optional && TypeMapper.IsValueTypeScalar(field.ProtoType))
            return baseType + "?";

        return baseType;
    }

    private static string ResolveTypeRef(string protoType)
    {
        bool leadingDot = protoType.StartsWith('.');
        if (leadingDot) protoType = protoType[1..];

        string? scalar = TypeMapper.ScalarToCSharp(protoType);
        if (scalar != null) return scalar;

        if (protoType.Contains('.'))
        {
            var parts = protoType.Split('.');
            for (int i = 0; i < parts.Length; i++)
                parts[i] = NameConverter.ToPascalCase(parts[i]);
            return string.Join('.', parts);
        }

        return protoType;
    }

    private static string? GetInitializer(ProtoField field, string csharpType)
    {
        if (field.IsMap)
            return $"new {csharpType}()";

        if (field.Label == FieldLabel.Repeated)
            return $"new {csharpType}()";

        if (field.Label == FieldLabel.Optional)
            return null;

        if (field.ProtoType == "string")
            return "\"\"";

        if (field.ProtoType == "bytes")
            return "Array.Empty<byte>()";

        return null;
    }
}
